modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: dnf
    repos:
      files:
        - docker-ce.repo
      keys:
        - https://download.docker.com/linux/fedora/gpg
    group-install:
      with-optional: true
      packages:
        - development-tools
        - c-development
    remove:
      packages:
        - moby-engine
        - docker-cli
    install:
      packages:
        - usbguard
        - android-tools
        - arm-image-installer
        - hunspell-devel
        - zsh
        - autofs
        - wireguard-tools
        - trash-cli
        - git
        - git-filter-repo
        - firewall-config
        - alsa-tools
        - libappstream-glib
        - htop
        - glances
        - ansible
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        # temporarily disabled due to upstream bug: https://github.com/fedora-selinux/selinux-policy/issues/3081
        #- freeipa-client
        - chromium-headless
        - python3
        - python3-devel
        - openssl
        - samba
        - ncdu
  - type: systemd
    system:
      enabled:
        - docker.service
        - firstboot-sshd.service
        - sshd.service
  - type: signing
