[hostiqo]
image=quay.io/rockylinux/rockylinux:9-ubi-init
init=true
nvidia=false
pull=true
root=true
start_now=false
# Persistent Laravel app and storage on host's writable /var.
volume="/var/lib/hostiqo:/var/www/hostiqo"
